// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Follow struct {
	UserID     int64 `json:"user_id"`
	FollowerID int64 `json:"follower_id"`
}

type Tweet struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	// Content of the post
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Passhash  string    `json:"passhash"`
	FullName  string    `json:"full_name"`
	CreatedAt time.Time `json:"created_at"`
}
